config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: 'home#index'

  get '/server', to: 'server#index'
  get '/server/start', to: 'server#start'
  get '/server/stop', to: 'server#stop'
  get '/server/status', to: 'server#status'

  get '/experience', to: 'experience#get_experience'

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  scope :roots, -> { where(parent_id: -1) }

	def is_root?
		parent_id == -1
	end

  def children
    Experience.where(parent_id: id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :user_user_role
  has_many :user_role, :through => :user_user_role

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
	has_many :user_user_role
	has_many :user, :through => :user_user_role
end

app/models/user_user_role.rb
class UserUserRole < ActiveRecord::Base
	belongs_to :user
	belongs_to :user_role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experience_controller.rb
class ExperienceController < ApplicationController
  #Build experience
  def get_experience
    respond_to do |format|
      format.html {render nothing: true}
      format.json do
        experience = Experience.roots 
        experience = experience.map{|exp| {name: exp.name, children: exp.children.map{|child| {name: child.name, size: child.value}}}}
        return render(json: {name: "experience", children: experience})
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/server_controller.rb
class ServerController < ApplicationController
  def index
  end

  def start
    result = `/home/shared/start_server.sh`
    respond_to do |format|
      format.html{render nothing: true}
      format.json{render json: [result]}
    end
  end

  def stop
    result = `/home/shared/stop_server.sh`
    respond_to do |format|
      format.html{render nothing: true}
      format.json{render json: [result]}
    end
  end

  def status
    status = `/home/shared/server_status`.to_bool
    respond_to do |format|
      format.html{render nothing: true}
      format.json{render json: status}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experience_helper.rb
module ExperienceHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/server_helper.rb
module ServerHelper
end

app/views/home/index.html.haml
#experience

%div.editable

:javascript
  new BilevelPartition("/experience.json", "#experience");

app/views/layouts/application.html.haml
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:http_equiv => "X-UA-Compatible", :content => "IE=Edge,chrome=1"}
    %meta{:name =>"viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : "PersonalWebsite"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all" 
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' 
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' 
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' 
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' 

    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' 

    = javascript_include_tag "application" 
  %body
    %div.navbar.navbar-default.navbar-static-top
      %div.container
        %button.navbar-toggle{:type =>"button", :data_toggle =>"collapse", :data_target =>".navbar-responsive-collapse"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href =>"#PersonalWebsite"}
        %div.navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "MCServer", "/server"  
    %div.container
      %div.row
        %div.col-lg-9
          = bootstrap_flash
          = yield
        %div.col-lg-3
          %div.well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar

app/views/server/index.html.haml
%span
  Server Status:
%span#status
      

.buttons
  %button.start-button Start
  %button.stop-button Stop

:javascript
  var init_server_status = function(){
    var update_status = function() {
      $.ajax("/server/status.json",
        {complete: function(response){ $('#status').text(response.responseJSON ? "Server running" : "Server stopped") }}
      );};
    update_status();

    var disable = function(jqueryObject){
      jqueryObject.attr("disabled", "disabled")
    }
    var enable = function(jqueryObject){
      jqueryObject.removeAttr("disabled")
    }

    var complete = function(response){
        alert(response.responseJSON);
        update_status();
      };

    var clickFunction = function(enableButton, disableButton, json){
        disable($(disableButton));
        enable($(enableButton));
        $.ajax(json, {complete: complete})
      }

    $('.start-button').click(function(){
      clickFunction('.stop-button', '.start-button', "#{server_start_path :format => "json"}");
    });

    $('.stop-button').click(function(){
      clickFunction('.start-button', '.stop-button', "#{server_stop_path :format => "json"}");
    });
  };

  init_server_status();
  init_server_status = null;